// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AntDto } from "./AntDto";
import type { FoodSourceDto } from "./FoodSourceDto";
import type { NestDto } from "./NestDto";
import type { StatsDto } from "./StatsDto";

export type WorldDto = { nest: NestDto, foodSources: Array<FoodSourceDto>, ants: Array<AntDto>, width: number, height: number, stats: StatsDto, };