// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AntDto } from "./AntDto";
import type { NestDto } from "./NestDto";

export type WorldDto = {
  nest: NestDto;
  ants: Array<AntDto>;
  width: number;
  height: number;
};
