// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AntStateDto } from "./AntStateDto";

export type AntDto = { id: number, x: number, y: number, state: AntStateDto, health: number, };