// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SimulationOptions = { width: number, height: number, startingAnts: number, startingFoodSources: number, maxFoodSources: number, };
