[package]
name = "wasm-client"
version = "0.1.0"
description = "wasm client for the simulation"
authors = ["Connor Flowers"]
repository = "https://github.com/c-florist/formicarium/tree/main/packages/wasm-client"
edition = "2024"
rust-version = "1.88.0"

[lib]
crate-type = ["cdylib", "rlib"]

[profile.dev]
incremental = true

[dependencies]
simulation = { path = "../simulation" }

# Dependencies for WASM interaction
wasm-bindgen = { version = "0.2", features = ["serde-serialize"] }
serde = { version = "1.0", features = ["derive"] }
serde-wasm-bindgen = "0.6"
console_error_panic_hook = { version = "0.1", optional = true }

[features]
default = ["console_error_panic_hook"]
