[package]
name = "formicarium"
version = "0.1.0"
description = "[noun]: an ant's nest, especially one in an artificial container for purposes of study."
authors = ["Connor Flowers"]
license = ""
repository = "https://github.com/kyoh-dev/formicarium"
edition = "2024"
rust-version = "1.88.0"

[lib]
name = "formicarium_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.3.0", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
tauri = { version = "2.6.2", features = [] }
tauri-plugin-log = "2"
hecs = "0.10"
rand = "0.9"
rand_pcg = "0.9"
ts-rs = { version = "8.0", features = ["serde-compat"] }
once_cell = "1.21.3"
