[package]
name = "core-rs"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
hecs = "0.10"
rand = "0.9"
rand_pcg = "0.9"
serde = { version = "1.0", features = ["derive"] }
serde-wasm-bindgen = "0.6"
ts-rs = { version = "8.0", features = ["serde-compat"] }
wasm-bindgen = { version = "0.2", features = ["serde-serialize"] }

[target.wasm32-unknown-unknown.dependencies]
getrandom = { version = "0.3", features = ["wasm_js"] }
