name: formicarium CI
on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  build-core:
    name: Build core
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@57951197789633361d699a72e3214257ead117cf
        with:
          toolchain: stable

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@b96e24233c3f44b2ac39038a7de3c5d272038d5d

      - name: Install wasm-pack
        uses: jetli/wasm-pack-action@f8d7c304d7548513b4897a508382351944516129

      - name: Build wasm package
        run: wasm-pack build ./packages/core-rs --out-dir ./pkg

      - name: Upload pkg artifact
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b583c30229
        with:
          name: pkg
          path: packages/core-rs/pkg

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: build-core
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@57951197789633361d699a72e3214257ead117cf
        with:
          toolchain: stable

      - name: Download pkg artifact
        uses: actions/download-artifact@8f2b2b23f41831a294b79d8383a4a73c80201dce
        with:
          name: pkg
          path: packages/core-rs/pkg

      - name: Setup pnpm
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda
        with:
          version: 10.12

      - name: Use Node.js
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af
        with:
          node-version: 22.11
          cache: 'pnpm'

      - name: Install node modules
        run: pnpm install

      - name: Run Biome check
        run: pnpm run tidy:check

      - name: Run rustfmt check
        run: cargo fmt --manifest-path packages/core-rs/Cargo.toml -- --check

  typecheck:
    name: Typecheck
    runs-on: ubuntu-latest
    needs: build-core
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Download pkg artifact
        uses: actions/download-artifact@8f2b2b23f41831a294b79d8383a4a73c80201dce
        with:
          name: pkg
          path: packages/core-rs/pkg

      - name: Setup pnpm
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda
        with:
          version: 10.12

      - name: Use Node.js
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af
        with:
          node-version: 22.11
          cache: 'pnpm'

      - name: Install node modules
        run: pnpm install

      - name: Run typecheck
        run: pnpm run typecheck

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build-core
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@57951197789633361d699a72e3214257ead117cf
        with:
          toolchain: stable

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@b96e24233c3f44b2ac39038a7de3c5d272038d5d

      - name: Download pkg artifact
        uses: actions/download-artifact@8f2b2b23f41831a294b79d8383a4a73c80201dce
        with:
          name: pkg
          path: packages/core-rs/pkg

      - name: Setup pnpm
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda
        with:
          version: 10.12

      - name: Use Node.js
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af
        with:
          node-version: 22.11
          cache: 'pnpm'

      - name: Install node modules
        run: pnpm install

      - name: Run TypeScript unit tests
        run: pnpm --filter "@formicarium/*" test:unit

      - name: Build Rust binaries
        run: cargo build --manifest-path packages/core-rs/Cargo.toml

      - name: Run Rust unit tests
        run: cargo test --manifest-path packages/core-rs/Cargo.toml
