name: formicarium CI
on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  build-core:
    name: Build core
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@1.88.0
        with:
          toolchain: stable

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@98c8021b550208e191a6a3145459bfc9fb29c4c0

      - name: Install wasm-pack
        run: cargo install wasm-pack

      - name: Build wasm package
        run: wasm-pack build ./packages/core-rs --out-dir ./pkg

      - name: Upload pkg artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: pkg
          path: packages/core-rs/pkg

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: build-core
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@1.88.0
        with:
          toolchain: stable

      - name: Download pkg artifact
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093
        with:
          name: pkg
          path: packages/core-rs/pkg

      - name: Setup pnpm
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda
        with:
          version: 10.12

      - name: Use Node.js
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af
        with:
          node-version: 22.11
          cache: 'pnpm'

      - name: Install node modules
        run: pnpm install

      - name: Run Biome check
        run: pnpm run tidy:check

      - name: Run rustfmt check
        run: cargo fmt --manifest-path packages/core-rs/Cargo.toml -- --check

  typecheck:
    name: Typecheck
    runs-on: ubuntu-latest
    needs: build-core
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Download pkg artifact
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093
        with:
          name: pkg
          path: packages/core-rs/pkg

      - name: Setup pnpm
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda
        with:
          version: 10.12

      - name: Use Node.js
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af
        with:
          node-version: 22.11
          cache: 'pnpm'

      - name: Install node modules
        run: pnpm install

      - name: Run typecheck
        run: pnpm run typecheck

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build-core
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@1.88.0
        with:
          toolchain: stable

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@98c8021b550208e191a6a3145459bfc9fb29c4c0

      - name: Download pkg artifact
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093
        with:
          name: pkg
          path: packages/core-rs/pkg

      - name: Setup pnpm
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda
        with:
          version: 10.12

      - name: Use Node.js
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af
        with:
          node-version: 22.11
          cache: 'pnpm'

      - name: Install node modules
        run: pnpm install

      - name: Run TypeScript unit tests
        run: pnpm --filter "@formicarium/*" test:unit

      - name: Build Rust core
        run: cargo build --manifest-path packages/core-rs/Cargo.toml

      - name: Run Rust unit tests
        run: cargo test --manifest-path packages/core-rs/Cargo.toml
